/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Liveness + dependency probe
         * @description Returns 200 with DB and Redis probe results. Used by the docker-compose healthcheck and the liveness Kubernetes probe. No auth.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Service is up; reports DB + Redis reachability. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: {
                                /** @enum {string} */
                                readonly status: PathsApiV1HealthGetResponses200ContentApplicationJsonDataStatus;
                                /** @enum {string} */
                                readonly db: PathsApiV1HealthGetResponses200ContentApplicationJsonDataDb;
                                /** @enum {string} */
                                readonly redis: PathsApiV1HealthGetResponses200ContentApplicationJsonDataRedis;
                                readonly uptime: number;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description At least one dependency is down. */
                readonly 503: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "SERVICE_UNAVAILABLE",
                         *         "message": "At least one dependency is down."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/wx-login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * WeChat login (jscode2session)
         * @description Exchanges a WeChat `code` for an `openid` via the WeChat jscode2session API, then issues or reuses a user record and returns an access token. Idempotent: re-login with the same `code` returns the same user.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly code: string;
                        readonly nickname?: string;
                        /** Format: uri */
                        readonly avatar?: string;
                        /** @description E.164-ish phone for unlock. */
                        readonly phone?: string;
                    };
                };
            };
            readonly responses: {
                /** @description New or existing user authenticated. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: {
                                /** @description Access JWT (15-min TTL). */
                                readonly token: string;
                                /** @description Refresh token (30-day TTL). */
                                readonly refreshToken?: string;
                                readonly user: components["schemas"]["User"];
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description WeChat jscode2session returned 40029. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "INVALID_CODE",
                         *         "message": "WeChat jscode2session returned 40029."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description 10 req/min per IP. */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "LOGIN_RATE_LIMITED",
                         *         "message": "10 req/min per IP."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/apple-login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Apple Sign-In (id_token verify)
         * @description Verifies the Apple `id_token` and issues or reuses a user record.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly idToken: string;
                        readonly fullName?: string;
                        readonly phone?: string;
                    };
                };
            };
            readonly responses: {
                /** @description Authenticated. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["User"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Apple id_token verify failed. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "INVALID_ID_TOKEN",
                         *         "message": "Apple id_token verify failed."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/google-login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Google Sign-In (id_token verify)
         * @description Verifies the Google `id_token` and issues or reuses a user record.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly idToken: string;
                        readonly phone?: string;
                    };
                };
            };
            readonly responses: {
                /** @description Authenticated. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["User"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Google id_token verify failed. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "INVALID_ID_TOKEN",
                         *         "message": "Google id_token verify failed."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/refresh": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Rotate access + refresh tokens
         * @description Validates the `refresh_token` and its `jti` against Redis, then issues a new access/refresh pair and replaces the stored jti. Returns 410 if the user has been soft-deleted.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly refreshToken: string;
                    };
                };
            };
            readonly responses: {
                /** @description New tokens issued. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: {
                                readonly token: string;
                                readonly refreshToken: string;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description refresh_token invalid or already consumed. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "refresh_token invalid or already consumed."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description User has been soft-deleted. */
                readonly 410: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACCOUNT_DELETED",
                         *         "message": "User has been soft-deleted."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Consume the current refresh_token (idempotent)
         * @description Deletes the `jti` from Redis if present. Calling twice is a no-op (still 200).
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly refreshToken: string;
                    };
                };
            };
            readonly responses: {
                /** @description Logged out (idempotent). */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: Record<string, never>;
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No access token. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "No access token."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/link-provider": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Bind an additional login provider (planned)
         * @description Spec endpoint #6 — bind an extra provider to the current user. **Not implemented yet**; the underlying schema is single-openid. Will land in a follow-up after the IdentityProvider table is added.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        /** @enum {string} */
                        readonly provider: PathsApiV1AuthLinkProviderPostRequestBodyContentApplicationJsonProvider;
                        readonly providerSub: string;
                    };
                };
            };
            readonly responses: {
                /** @description Provider bound. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The (provider, sub) is already owned by another user. */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "PROVIDER_ALREADY_LINKED",
                         *         "message": "The (provider, sub) is already owned by another user."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Cannot unlink the user's last login method. */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "LAST_PROVIDER",
                         *         "message": "Cannot unlink the user's last login method."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/users/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Current user profile */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Profile. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["User"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Token missing or invalid. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Token missing or invalid."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Token sub has no row (or user is DELETED). */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "USER_NOT_FOUND",
                         *         "message": "Token sub has no row (or user is DELETED)."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        /**
         * Soft-delete the current account
         * @description Marks the user `DELETED` with `deletedAt = now()`. Idempotent: a second call returns the original `deletedAt` without re-writing the row. All active access tokens (≤15-min TTL) will be rejected by `authenticate()`.
         */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Soft-deleted. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: {
                                /** Format: date-time */
                                readonly deletedAt: string;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Token missing or invalid. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Token missing or invalid."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        /**
         * Update mutable profile fields
         * @description Strict schema: at least one of `nickname` / `avatar` / `school` / `major` / `grade` / `bio` must be present. Email and phone are NOT updatable here.
         */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly nickname?: string;
                        /** Format: uri */
                        readonly avatar?: string;
                        readonly school?: string;
                        readonly major?: string;
                        readonly grade?: string;
                        readonly bio?: string;
                    };
                };
            };
            readonly responses: {
                /** @description Updated profile. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["User"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Empty body or extra keys. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Empty body or extra keys."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Token missing or invalid. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Token missing or invalid."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/api/v1/users/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Public profile (auth optional)
         * @description Returns the public profile. If a valid bearer token is sent, `viewerId` is propagated so the service can return viewer-aware fields. Returns 404 for DELETED users (no probe).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description User id (cuid with `usr_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Public profile. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["User"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No such user (or DELETED). */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "USER_NOT_FOUND",
                         *         "message": "No such user (or DELETED)."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/users/me/activities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** My activities (created or joined) */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description `created` lists activities I created; `joined` lists activities I signed up for. */
                    readonly type?: PathsApiV1UsersMeActivitiesGetParametersQueryType;
                    readonly page?: number;
                    readonly pageSize?: number;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Page of activities. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: readonly components["schemas"]["Activity"][];
                            readonly total: number;
                            readonly page: number;
                            readonly pageSize: number;
                            readonly hasMore?: boolean;
                        };
                    };
                };
                /** @description Token missing or invalid. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Token missing or invalid."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/activities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List activities (paged, filterable, geo-sortable) */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly type?: PathsApiV1ActivitiesGetParametersQueryType;
                    readonly status?: PathsApiV1ActivitiesGetParametersQueryStatus;
                    readonly school?: string;
                    readonly keyword?: string;
                    readonly start_after?: string;
                    readonly start_before?: string;
                    readonly lat?: number;
                    readonly lng?: number;
                    readonly radius_km?: number;
                    readonly sort?: PathsApiV1ActivitiesGetParametersQuerySort;
                    readonly page?: number;
                    readonly page_size?: number;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Page of activities. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: {
                                readonly data: readonly components["schemas"]["Activity"][];
                                readonly total: number;
                                readonly page: number;
                                readonly pageSize: number;
                                readonly hasMore?: boolean;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        /** Create an activity */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        /** @enum {string} */
                        readonly type: PathsApiV1ActivitiesPostRequestBodyContentApplicationJsonType;
                        readonly title: string;
                        readonly description?: string;
                        readonly locationName: string;
                        readonly locationAddr?: string;
                        readonly locationLat: number;
                        readonly locationLng: number;
                        /** Format: date-time */
                        readonly startTime: string;
                        /** Format: date-time */
                        readonly endTime: string;
                        readonly maxParticipants: number;
                        readonly tags?: readonly string[];
                    };
                };
            };
            readonly responses: {
                /** @description Created. */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["Activity"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Body failed zod validation. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Body failed zod validation."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Token missing or invalid. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHORIZED",
                         *         "message": "Token missing or invalid."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description 10 activities per hour per user. */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "CREATE_RATE_LIMITED",
                         *         "message": "10 activities per hour per user."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/activities/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Activity detail */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Activity id (cuid with `act_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Activity. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["Activity"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No such activity. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_FOUND",
                         *         "message": "No such activity."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        /** Cancel activity (creator only) */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Activity id (cuid with `act_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Canceled. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["Activity"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Caller is not the creator. */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "Caller is not the creator."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No such activity. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_FOUND",
                         *         "message": "No such activity."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description >1h before start_time; cannot cancel. */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "CANCEL_TOO_LATE",
                         *         "message": ">1h before start_time; cannot cancel."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        /** Modify activity (creator only) */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Activity id (cuid with `act_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly title?: string;
                        readonly description?: string;
                        readonly locationName?: string;
                        readonly locationAddr?: string;
                        /** Format: date-time */
                        readonly startTime?: string;
                        /** Format: date-time */
                        readonly endTime?: string;
                        readonly maxParticipants?: number;
                        readonly tags?: readonly string[];
                    };
                };
            };
            readonly responses: {
                /** @description Updated. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["Activity"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Caller is not the creator. */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "Caller is not the creator."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No such activity. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_FOUND",
                         *         "message": "No such activity."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description >1h before start_time; cannot cancel. */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "CANCEL_TOO_LATE",
                         *         "message": ">1h before start_time; cannot cancel."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/api/v1/activities/{id}/signup": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Sign up for an activity */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Activity id (cuid with `act_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody: {
                readonly content: {
                    readonly "application/json": {
                        readonly message?: string;
                    };
                };
            };
            readonly responses: {
                /** @description Signed up. */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["Signup"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No such activity. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_FOUND",
                         *         "message": "No such activity."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Caller is already signed up. */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ALREADY_SIGNED_UP",
                         *         "message": "Caller is already signed up."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Status is not RECRUITING/FULL, or activity is full. */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_OPEN",
                         *         "message": "Status is not RECRUITING/FULL, or activity is full."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description 30 signups per hour per user. */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "SIGNUP_RATE_LIMITED",
                         *         "message": "30 signups per hour per user."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        /** Cancel my signup */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Activity id (cuid with `act_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Cancelled. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: components["schemas"]["Signup"];
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Caller was not signed up. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "SIGNUP_NOT_FOUND",
                         *         "message": "Caller was not signed up."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Activity is STARTED or ENDED. */
                readonly 422: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_CANCELABLE",
                         *         "message": "Activity is STARTED or ENDED."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/activities/{id}/participants": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List participants (public) */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    readonly page?: number;
                    readonly pageSize?: number;
                };
                readonly header?: never;
                readonly path: {
                    /** @description Activity id (cuid with `act_` prefix in the seed). */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Page of participants. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly data: {
                                readonly data: readonly components["schemas"]["Signup"][];
                                readonly total: number;
                                readonly page: number;
                                readonly pageSize: number;
                                readonly hasMore?: boolean;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description No such activity. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "ACTIVITY_NOT_FOUND",
                         *         "message": "No such activity."
                         *       },
                         *       "meta": {
                         *         "requestId": "req_4f2c",
                         *         "timestamp": "2026-06-29T12:00:00.000Z"
                         *       }
                         *     }
                         */
                        readonly "application/json": {
                            readonly error: {
                                /** @example VALIDATION_ERROR */
                                readonly code: string;
                                /** @example 请求参数校验失败 */
                                readonly message: string;
                                readonly details?: {
                                    readonly [key: string]: unknown;
                                } | null;
                            };
                            readonly meta?: components["schemas"]["Meta"];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly Meta: {
            /** @example req_4f2c */
            readonly requestId: string;
            /** Format: date-time */
            readonly timestamp: string;
        };
        readonly User: {
            /** @example usr_abc */
            readonly id: string;
            readonly nickname: string;
            /** Format: uri */
            readonly avatar?: string | null;
            readonly school?: string | null;
            readonly major?: string | null;
            readonly grade?: string | null;
            readonly bio?: string | null;
            /** @enum {string} */
            readonly role: UserRole;
            /** @enum {string} */
            readonly status: UserStatus;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly deletedAt?: string | null;
        };
        readonly Creator: {
            readonly id: string;
            readonly nickname: string;
            /** Format: uri */
            readonly avatar?: string | null;
        };
        readonly Activity: {
            /** @example act_abc123 */
            readonly id: string;
            readonly creator: components["schemas"]["Creator"];
            /** @enum {string} */
            readonly type: ActivityType;
            readonly title: string;
            readonly description?: string;
            readonly locationName?: string;
            readonly locationAddr?: string;
            readonly locationLat?: number;
            readonly locationLng?: number;
            /** Format: date-time */
            readonly startTime: string;
            /** Format: date-time */
            readonly endTime: string;
            readonly maxParticipants: number;
            readonly currentCount: number;
            /** @enum {string} */
            readonly status: ActivityStatus;
            readonly tags?: readonly string[];
            /** Format: date-time */
            readonly createdAt: string;
        };
        readonly Signup: {
            /** @example sgn_xxx */
            readonly id: string;
            readonly activityId: string;
            readonly user: components["schemas"]["Creator"];
            /** @enum {string} */
            readonly status: SignupStatus;
            readonly message?: string | null;
            /** Format: date-time */
            readonly signedAt: string;
        };
        readonly Pagination: {
            readonly total: number;
            readonly page: number;
            readonly pageSize: number;
            readonly hasMore?: boolean;
        };
    };
    responses: {
        /** @description No bearer token. */
        readonly Unauthorized: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "No bearer token."
                 *       },
                 *       "meta": {
                 *         "requestId": "req_4f2c",
                 *         "timestamp": "2026-06-29T12:00:00.000Z"
                 *       }
                 *     }
                 */
                readonly "application/json": {
                    readonly error: {
                        /** @example VALIDATION_ERROR */
                        readonly code: string;
                        /** @example 请求参数校验失败 */
                        readonly message: string;
                        readonly details?: {
                            readonly [key: string]: unknown;
                        } | null;
                    };
                    readonly meta?: components["schemas"]["Meta"];
                };
            };
        };
        /** @description Caller lacks permission. */
        readonly Forbidden: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "Caller lacks permission."
                 *       },
                 *       "meta": {
                 *         "requestId": "req_4f2c",
                 *         "timestamp": "2026-06-29T12:00:00.000Z"
                 *       }
                 *     }
                 */
                readonly "application/json": {
                    readonly error: {
                        /** @example VALIDATION_ERROR */
                        readonly code: string;
                        /** @example 请求参数校验失败 */
                        readonly message: string;
                        readonly details?: {
                            readonly [key: string]: unknown;
                        } | null;
                    };
                    readonly meta?: components["schemas"]["Meta"];
                };
            };
        };
        /** @description Resource not found. */
        readonly NotFound: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Resource not found."
                 *       },
                 *       "meta": {
                 *         "requestId": "req_4f2c",
                 *         "timestamp": "2026-06-29T12:00:00.000Z"
                 *       }
                 *     }
                 */
                readonly "application/json": {
                    readonly error: {
                        /** @example VALIDATION_ERROR */
                        readonly code: string;
                        /** @example 请求参数校验失败 */
                        readonly message: string;
                        readonly details?: {
                            readonly [key: string]: unknown;
                        } | null;
                    };
                    readonly meta?: components["schemas"]["Meta"];
                };
            };
        };
        /** @description Body failed zod validation. */
        readonly ValidationError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "Body failed zod validation."
                 *       },
                 *       "meta": {
                 *         "requestId": "req_4f2c",
                 *         "timestamp": "2026-06-29T12:00:00.000Z"
                 *       }
                 *     }
                 */
                readonly "application/json": {
                    readonly error: {
                        /** @example VALIDATION_ERROR */
                        readonly code: string;
                        /** @example 请求参数校验失败 */
                        readonly message: string;
                        readonly details?: {
                            readonly [key: string]: unknown;
                        } | null;
                    };
                    readonly meta?: components["schemas"]["Meta"];
                };
            };
        };
        /** @description Too many requests. */
        readonly RateLimited: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMIT_EXCEEDED",
                 *         "message": "Too many requests."
                 *       },
                 *       "meta": {
                 *         "requestId": "req_4f2c",
                 *         "timestamp": "2026-06-29T12:00:00.000Z"
                 *       }
                 *     }
                 */
                readonly "application/json": {
                    readonly error: {
                        /** @example VALIDATION_ERROR */
                        readonly code: string;
                        /** @example 请求参数校验失败 */
                        readonly message: string;
                        readonly details?: {
                            readonly [key: string]: unknown;
                        } | null;
                    };
                    readonly meta?: components["schemas"]["Meta"];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export enum PathsApiV1HealthGetResponses200ContentApplicationJsonDataStatus {
    ok = "ok",
    degraded = "degraded"
}
export enum PathsApiV1HealthGetResponses200ContentApplicationJsonDataDb {
    up = "up",
    down = "down"
}
export enum PathsApiV1HealthGetResponses200ContentApplicationJsonDataRedis {
    up = "up",
    down = "down"
}
export enum PathsApiV1AuthLinkProviderPostRequestBodyContentApplicationJsonProvider {
    WECHAT = "WECHAT",
    APPLE = "APPLE",
    GOOGLE = "GOOGLE"
}
export enum PathsApiV1UsersMeActivitiesGetParametersQueryType {
    created = "created",
    joined = "joined"
}
export enum PathsApiV1ActivitiesGetParametersQueryType {
    STUDY = "STUDY",
    SPORTS = "SPORTS",
    BOARD_GAME = "BOARD_GAME",
    ONLINE_GAME = "ONLINE_GAME",
    OTHER = "OTHER"
}
export enum PathsApiV1ActivitiesGetParametersQueryStatus {
    RECRUITING = "RECRUITING",
    FULL = "FULL",
    STARTED = "STARTED",
    ENDED = "ENDED",
    CANCELED = "CANCELED"
}
export enum PathsApiV1ActivitiesGetParametersQuerySort {
    time_asc = "time_asc",
    time_desc = "time_desc",
    distance_asc = "distance_asc",
    created_desc = "created_desc"
}
export enum PathsApiV1ActivitiesPostRequestBodyContentApplicationJsonType {
    STUDY = "STUDY",
    SPORTS = "SPORTS",
    BOARD_GAME = "BOARD_GAME",
    ONLINE_GAME = "ONLINE_GAME",
    OTHER = "OTHER"
}
export enum UserRole {
    USER = "USER",
    ADMIN = "ADMIN"
}
export enum UserStatus {
    ACTIVE = "ACTIVE",
    BANNED = "BANNED",
    DELETED = "DELETED"
}
export enum ActivityType {
    STUDY = "STUDY",
    SPORTS = "SPORTS",
    BOARD_GAME = "BOARD_GAME",
    ONLINE_GAME = "ONLINE_GAME",
    OTHER = "OTHER"
}
export enum ActivityStatus {
    RECRUITING = "RECRUITING",
    FULL = "FULL",
    STARTED = "STARTED",
    ENDED = "ENDED",
    CANCELED = "CANCELED"
}
export enum SignupStatus {
    APPROVED = "APPROVED",
    CANCELED = "CANCELED",
    KICKED = "KICKED"
}
export type operations = Record<string, never>;
