// Bulk-transform src files that import the old frozen `env` from
// `@/lib/env.js` / `./env.js` into the new lazy `getEnv()` API.
//
// Run from the repo root (server/) via: `node scripts/refactor-env.mjs`
//
// Idempotent: re-running on already-refactored files is a no-op
// because the new import line uses `getEnv`, not `env`.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// Files we know import `env` from `@/lib/env.js` or `./env.js`.
// Paths are relative to server/. Generated by grep.
const FILES = [
  'src/server.ts',
  'src/lib/prisma.ts',
  'src/lib/redis.ts',
  'src/lib/logger.ts',
  'src/lib/app.ts',
  'src/lib/sentry.ts',
  'src/plugins/auth.ts',
  'src/plugins/cors.ts',
  'src/plugins/rate-limit.ts',
  'src/plugins/error-handler.ts',
  'src/modules/signup/index.ts',
  'src/modules/review/review.routes.ts',
  'src/modules/auth/index.ts',
  'src/modules/activity/index.ts',
];

// Pattern A: `import { env } from '...'` -> `import { getEnv } from '...'`
const IMPORT_RE = /^import\s+\{\s*env\s*\}\s+from\s+(['"])([^'"]+)\1\s*;?$/gm;
function rewriteImports(src) {
  let changed = false;
  const next = src.replace(IMPORT_RE, (full, quote, spec) => {
    changed = true;
    return `import { getEnv } from ${quote}${spec}${quote};`;
  });
  return { src: next, changed };
}

// Pattern B: `env.X` -> `getEnv().X` for every identifier access.
// We do NOT touch:
//   - `env` inside string literals (template strings + '...' / "...")
//   - `env` inside comments (the env.JWT_SECRET doc references in
//     monitoring/index.ts, content-safety.ts, etc. should stay as
//     text).
// We use a regex that only matches `env` followed by `.IDENT`,
// OUTSIDE of line/block comments and string literals.  We keep it
// conservative: we transform line-by-line, skipping any line whose
// first non-whitespace is `//` (a pure comment line), and ignoring
// matches inside backtick template strings or quoted strings.
//
// For our 14 files, the only `env.X` reads are code, not comments,
// so a simpler line-scoped regex is safe:
//   replace /(?<![A-Za-z0-9_$.'"`])env\.([A-Z_][A-Z0-9_]*)/g
// with `getEnv().$1`
//
// The negative lookbehind keeps `foo.env` / `'env.'` / `"env."` /
// backtick `` `env.` `` untouched.
const ACCESS_RE = /(?<![A-Za-z0-9_$.'"`])env\.([A-Z_][A-Z0-9_]*)/g;
function rewriteAccess(src) {
  let changed = false;
  const next = src.replace(ACCESS_RE, (_full, name) => {
    changed = true;
    return `getEnv().${name}`;
  });
  return { src: next, changed };
}

let totalFiles = 0;
let totalFilesChanged = 0;
let totalAccessRewrites = 0;
for (const rel of FILES) {
  const path = resolve(ROOT, rel);
  const before = readFileSync(path, 'utf8');
  const imp = rewriteImports(before);
  const acc = rewriteAccess(imp.src);
  if (imp.changed || acc.changed) {
    writeFileSync(path, acc.src, 'utf8');
    totalFilesChanged += 1;
    // Count number of access rewrites in this file by comparing
    // occurrences of getEnv(). before/after.
    const beforeCount = (imp.src.match(ACCESS_RE) ?? []).length;
    totalAccessRewrites += beforeCount;
    console.log(`refactored: ${rel} (${beforeCount} access rewrites)`);
  } else {
    console.log(`unchanged:  ${rel}`);
  }
  totalFiles += 1;
}

console.log(`\n${totalFilesChanged}/${totalFiles} files changed, ${totalAccessRewrites} access rewrites`);