// User data model.
//
// Freezed gives us copyWith, ==, hashCode, and a `fromJson`/`toJson` round
// trip for free. The `.freezed.dart` and `.g.dart` files are generated by
// `dart run build_runner build` — see docs/flutter/dev-setup.md.

import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    required String id,
    @JsonKey(name: 'nickname') String? nickname,
    @JsonKey(name: 'avatar_url') String? avatarUrl,
    @JsonKey(name: 'school') String? school,
    @JsonKey(name: 'major') String? major,
    @JsonKey(name: 'bio') String? bio,
    @JsonKey(name: 'created_at') DateTime? createdAt,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
